create table movie (
	id INT NOT NULL auto_increment primary key,
	name VARCHAR(100) NOT NULL,
	genre VARCHAR(50) NOT NULL,
	movie_id VARCHAR(50) NOT NULL,
	availability boolean NOT NULL,
	next_available_time DATE
);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (1, 'Backstage', 'Drama', '68828-170', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (2, 'Alligator People, The', 'Horror', '11489-085', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (3, 'King of Kong, The', 'Documentary', '0113-0825', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (4, 'Three Crowns of the Sailor (Les trois couronnes du matelot)', 'Drama|Fantasy', '43857-0212', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (5, 'Back to the Future', 'Sci-Fi', '52125-389', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (6, 'Novo', 'Drama', '61657-0972', false, '2021-08-10');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (7, 'Story of a Prostitute (Shunpu den)', 'Drama|War', '63629-1485', false, '2021-08-20');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (8, 'Berlin 36', 'Drama', '24236-994', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (9, 'X', 'Thriller', '53808-0873', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (10, 'Tiger Eyes', 'Drama', '0113-0463', false, '2021-08-14');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (11, 'Thirty-Five Something (Tout pour plaire)', 'Comedy', '64117-535', false, '2021-09-15');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (12, 'Out of Reach', 'Action|Drama|Romance|Thriller', '22557-002', false, '2021-08-07');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (13, 'Home of the Brave', 'Documentary', '65113-2428', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (14, 'Bikini Summer III - South Beach Heat', 'Comedy', '69106-110', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (15, 'Along the Sungari River (Song hua jiang shang)', 'Drama', '60258-001', false, '2021-09-01');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (16, 'Tesla: Master of Lightning', 'Documentary', '50436-3099', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (17, 'Miss Pettigrew Lives for a Day', 'Comedy|Romance', '0268-1494', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (18, 'Everything or Nothing: The Untold Story of 007', 'Documentary', '55714-2307', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (19, 'Monsters', 'Drama|Sci-Fi', '43269-631', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (20, 'This Night I''ll Possess Your Corpse (Esta Noite Encarnarei no Teu Cadáver)', 'Horror', '69149-102', false, '2021-08-22');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (21, 'Rush Hour', 'Comedy', '52959-271', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (22, 'Landlord, The', 'Comedy|Drama', '40076-949', false, '2021-07-28');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (23, 'GoodFellas', 'Crime|Drama', '0498-0113', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (24, 'White Noise', 'Drama|Horror|Mystery|Sci-Fi|Thriller', '68788-9220', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (25, 'Samson and Delilah', 'Adventure|Drama', '0517-0770', false, '2021-09-28');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (26, 'At the Death House Door', 'Documentary', '0378-2670', false, '2021-08-06');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (27, 'West of Memphis', 'Documentary', '10812-024', false, '2021-09-21');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (28, 'Anatomy of Hell (Anatomie de l''enfer)', 'Drama', '43538-250', false, '2021-09-08');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (29, 'Summer of the Monkeys', 'Children|Drama', '64764-251', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (30, 'Defender, The', 'Action', '65044-2309', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (31, 'Fists in the Pocket (Pugni in tasca, I)', 'Drama', '0041-0241', false, '2021-09-01');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (32, 'Dead Birds', 'Horror|War|Western', '36800-057', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (33, 'I Travel Alone', 'Drama', '63304-644', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (34, 'Rocky', 'Sports|Drama', '0363-0341', false, '2021-08-12');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (35, 'Project Grizzly', 'Documentary', '55154-3728', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (36, 'Mother (Madeo)', 'Crime|Drama|Mystery|Thriller', '43547-274', false, '2021-08-22');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (37, 'Wanted', 'Action|Thriller', '0363-4007', false, '2021-09-16');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (38, 'Keeping Up with the Steins', 'Comedy', '52686-293', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (39, 'Happy Together', 'Drama|Romance', '50353-102', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (40, 'Dying of the Light', 'Drama|Thriller', '68084-225', false, '2021-09-04');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (41, 'Haunted World of El Superbeasto, The', 'Action|Animation|Comedy|Horror|Thriller', '0338-0355', false, '2021-09-04');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (42, 'Encino Man', 'Comedy', '0310-0751', false, '2021-09-04');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (43, 'SS Camp 5: Women''s Hell (SS Lager 5: L''inferno delle donne)', 'Drama|Thriller|War', '12546-720', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (44, 'BBOY for LIFE', 'Adventure|Crime|Documentary|Drama', '21130-314', false, '2021-08-31');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (45, 'Infernal Affairs III (Mou gaan dou III: Jung gik mou gaan)', 'Action|Crime|Drama|Thriller', '52125-668', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (46, 'Dragon Ball: Sleeping Princess in Devil''s Castle (Doragon bôru: Majinjô no nemuri hime)', 'Action|Adventure|Animation|Children', '0220-9134', false, '2021-08-12');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (47, '30 Days of Night: Dark Days', 'Horror|Thriller', '0517-1355', false, '2021-07-27');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (48, 'Hudson Hawk', 'Action|Adventure|Comedy', '67751-102', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (49, 'Ong Bak', 'Kung-Fu', '59734-271', false, '2021-08-31');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (50, 'Roadracers', 'Drama', '37012-526', false, '2021-09-19');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (51, 'Christmas Carol, A', 'Children|Drama|Fantasy', '0713-0701', false, '2021-09-04');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (52, 'Sink or Swim', 'Documentary', '67457-456', false, '2021-07-26');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (53, 'Beneath the Valley of the Ultra-Vixens', 'Comedy', '10738-301', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (54, 'Looking for Comedy in the Muslim World', 'Comedy', '57520-0840', false, '2021-09-04');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (55, 'Pitfall (Otoshiana)', 'Crime|Drama|Fantasy', '53808-0579', false, '2021-09-24');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (56, 'Finian''s Rainbow', 'Fantasy|Musical', '63629-2955', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (57, 'Doc Hollywood', 'Comedy|Romance', '45963-734', false, '2021-08-13');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (58, 'Wind, The', 'Drama|Western', '46672-228', false, '2021-09-27');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (59, 'Dark Knight', 'Action|Drama', '0049-4120', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (60, 'Blonde Ice', 'Film-Noir', '66530-253', false, '2021-08-09');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (61, 'Cabin Fever: Patient Zero', 'Horror|Sci-Fi|Thriller', '42858-902', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (62, 'Futurama: Bender''s Big Score', 'Animation|Comedy|Sci-Fi', '68788-9157', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (63, 'Trinity and Beyond', 'Documentary', '62011-0085', false, '2021-09-04');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (64, 'On Golden Pond', 'Drama', '50563-147', false, '2021-09-04');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (65, 'Dave', 'Comedy|Romance', '61314-395', false, '2021-08-29');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (66, 'Eaten Alive', 'Horror', '75936-116', false, '2021-08-14');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (67, 'Stonehenge Apocalypse', 'Sci-Fi', '62756-294', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (68, 'Atragon (Kaitei Gunkan)', 'Adventure|Sci-Fi', '53808-0411', false, '2021-08-03');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (69, 'How to Lose Friends & Alienate People', 'Comedy', '0591-3754', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (70, 'Way of the Dragon', 'Kung-Fu', '63868-711', false, '2021-08-22');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (71, 'Best of Times, The', 'Comedy|Drama', '0813-0202', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (72, 'At the Devil''s Door', 'Horror', '33992-0373', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (73, 'Scourge', 'Horror|Mystery|Sci-Fi', '60846-809', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (74, 'Land and Freedom (Tierra y libertad)', 'Drama|War', '50436-4605', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (75, 'Tommy', 'Drama|Musical', '0615-2528', false, '2021-09-26');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (76, 'Stacy', 'Comedy|Horror', '61578-301', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (77, 'Woyzeck', 'Drama', '0338-0003', false, '2021-08-10');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (78, 'Captain America', 'Action|Fantasy|Sci-Fi|Thriller|War', '11673-288', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (79, 'North and South, Book I', 'Drama|Romance|War', '43419-546', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (80, 'New York Confidential', 'Crime|Drama|Film-Noir', '64942-0891', false, '2021-09-12');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (81, 'Zazie dans le métro', 'Comedy', '0268-1260', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (82, 'Breakin''', 'Drama|Musical', '53877-006', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (83, 'Million Dollar Baby', 'Drama', '53346-1309', false, '2021-08-27');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (84, 'Growth', 'Sci-Fi|Thriller', '53808-0305', false, '2021-09-03');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (85, 'Last Days in the Desert', 'Adventure|Drama', '50804-190', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (86, 'Sun, The (Solntse)', 'Drama', '36987-2342', false, '2021-08-21');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (87, 'Battle Royale (Batoru rowaiaru)', 'Action|Drama|Horror|Thriller', '53346-1374', false, '2021-09-24');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (88, 'Eat', 'Documentary', '63323-495', false, '2021-09-04');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (89, 'Boys, Les', 'Comedy', '53217-021', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (90, 'Manborg', 'Action|Adventure|Comedy', '54622-698', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (91, 'Belly 2: Millionaire Boyz Club', 'Drama', '49349-648', false, '2021-08-31');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (92, 'Hell and Back Again', 'Documentary|Drama|War', '17156-602', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (93, 'And So It Goes', 'Comedy|Drama|Romance', '58232-6003', false, '2021-08-25');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (94, 'Princess Diaries 2: Royal Engagement, The', 'Comedy|Romance', '52979-8002', false, '2021-08-31');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (95, 'Return of the Musketeers, The', 'Adventure|Comedy', '43742-0242', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (96, 'We Can Be Heroes', '(no genres listed)', '0093-5769', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (97, 'Singapore Sling (Singapore sling: O anthropos pou agapise ena ptoma)', 'Crime|Film-Noir|Horror|Romance|Thriller', '10596-703', false, '2021-08-31');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (98, 'House of Women', 'Crime|Drama', '50112-515', false, '2021-09-05');
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (99, 'Woman Thou Art Loosed', 'Drama', '42023-134', true, null);
insert into movie (id, name, genre, movie_id, availability, next_available_time) values (100, 'Reservoir Dogs', 'Crime', '0007-4205', false, '2021-09-10');
